export const CANVAS_WIDTH = 1024;
export const CANVAS_HEIGHT = 384;

export const DEFAULT_PADDLE_WIDTH = 16;
export const DEFAULT_PADDLE_HEIGHT = 64;
export const PADDLE_EDGE_MARGIN = 0;

export const DEFAULT_PADDLE_MOVE_SPEED = 400;
export const DEFAULT_BALL_SPEED = 700;
export const DEFAULT_BALL_SIZE = 16;
export const DEFAULT_WINNING_SCORE = 3;
export const BALL_MASS = 5;

export const BALL_WAIT_TIME = 1; // seconds

export const BOT_DIFFICULTY = {
	EASY: { POLLING_RATE: 4, PREDICT_DISTANCE: 60, PADDLE_MOVE_SPEED: 320 },
	MEDIUM: { POLLING_RATE: 7, PREDICT_DISTANCE: 125, PADDLE_MOVE_SPEED: 400 },
	HARD: { POLLING_RATE: 11, PREDICT_DISTANCE: 225, PADDLE_MOVE_SPEED: 550 },
}